#! /usr/bin/env python

import sys
import argparse
from tectoolkit.fingerprint import FingerprintProgram
from tectoolkit.compare import CompareProgram
from tectoolkit.filter_gff import FilterGffProgram
from tectoolkit.preprocess import PreProcessProgram


def parse_program_arg(arg):
    """"""
    parser = argparse.ArgumentParser('Identify program to run')
    parser.add_argument('program',
                        type=str,
                        choices=("fingerprint", "compare", "filter_gff", "preprocess"))
    return parser.parse_args(arg)


def main():
    """"""
    if len(sys.argv) == 1:
        # default to simple help message
        program_arg = parse_program_arg([])
    else:
        program_arg = parse_program_arg([sys.argv[1]])

    program = program_arg.program
    if program == "fingerprint":
        job = FingerprintProgram(sys.argv[2:])
    elif program == "compare":
        job = CompareProgram(sys.argv[2:])
    elif program == "filter_gff":
        job = FilterGffProgram(sys.argv[2:])
    elif program == "preprocess":
        job = PreProcessProgram.from_cli(sys.argv[2:])
    job.run()

if __name__ == '__main__':
    main()
