#! /usr/bin/env python

import sys
import argparse
from tefingerprint.filtergff import FilterGffProgram
from tefingerprint.preprocess import PreProcessProgram
from tefingerprint.programs import FingerprintProgram
from tefingerprint.programs import ComparisonProgram


def parse_program_arg(arg):
    """"""
    parser = argparse.ArgumentParser('Identify program to run')
    parser.add_argument('program',
                        type=str,
                        choices=("preprocess",
                                 "fingerprint",
                                 "compare",
                                 "filter_gff"))
    return parser.parse_args(arg)


def main():
    """"""
    if len(sys.argv) == 1:
        # default to simple help message
        program_arg = parse_program_arg([])
    else:
        program_arg = parse_program_arg([sys.argv[1]])

    program = program_arg.program
    if program == "fingerprint":
        FingerprintProgram(sys.argv[2:])
    elif program == "compare":
        ComparisonProgram(sys.argv[2:])
    elif program == "filter_gff":
        FilterGffProgram(sys.argv[2:])
    elif program == "preprocess":
        job = PreProcessProgram.from_cli(sys.argv[2:])
        job.run()

if __name__ == '__main__':
    main()
