#! /usr/bin/env python

import sys
import argparse
from tefingerprint import _filter_gff
from tefingerprint.compression import zopen


def main():
    parser = argparse.ArgumentParser('Identify potential TE '
                                     'flanking regions')
    parser.add_argument('gff',
                        nargs=1,
                        help='A single gff file to be filtered')
    parser.add_argument('--all',
                        nargs='*',
                        help=('filters to apply to apply in the "all" '
                              'context. These should take the form '
                              '"<column><operator><value>".'),
                        default=[])
    parser.add_argument('--any',
                        nargs='*',
                        help=('filters to apply to apply in the "any" '
                              'context. These should take the form '
                              '"<column><operator><value>".'),
                        default=[])
    parser.add_argument('-o', '--output',
                        nargs=1,
                        help='A output file to write to. '
                             'Compression will be assumed by extension '
                             'e.g. ".gz" or ".bz2". '
                             'If this option is used then gff lines will '
                             'not be printed to standard out.',
                        default=[None])
    args = parser.parse_args(sys.argv[1:])

    all_filters = [_filter_gff.parse_filter_string(string)
                   for string in args.all]
    any_filters = [_filter_gff.parse_filter_string(string)
                   for string in args.any]

    with zopen(args.gff[0], 'rb') as f:
        output = args.output[0]
        if output:
            outfile = zopen(output, 'wb')
        for line in f:
            line = line.decode()
            feature = _filter_gff.parse_feature(line)

            if all_filters:
                all_true = _filter_gff.apply_filters(feature,
                                                     all_filters,
                                                     'ALL')
            else:
                all_true = True

            if any_filters:
                any_true = _filter_gff.apply_filters(feature,
                                                     any_filters,
                                                     'ANY')
            else:
                any_true = True

            if all_true and any_true:
                if output:
                    outfile.write(line.strip().encode() + b'\n')
                else:
                    print(line.strip())
        if output:
            outfile.close()


if __name__ == '__main__':
    main()
