#! /usr/bin/env python

import sys
import argparse
from tefingerprint import _filter_gff


def main():
    parser = argparse.ArgumentParser('Identify potential TE '
                                     'flanking regions')
    parser.add_argument('gff',
                        nargs=1,
                        help='A single gff file to be filtered')
    parser.add_argument('--all',
                        nargs='*',
                        help=('filters to apply to apply in the "all" '
                              'context. These should take the form '
                              '"<column><operator><value>".'),
                        default=[])
    parser.add_argument('--any',
                        nargs='*',
                        help=('filters to apply to apply in the "any" '
                              'context. These should take the form '
                              '"<column><operator><value>".'),
                        default=[])
    args = parser.parse_args(sys.argv[1:])

    all_filters = [_filter_gff.parse_filter_string(string)
                   for string in args.all]
    any_filters = [_filter_gff.parse_filter_string(string)
                   for string in args.any]

    with open(args.gff[0], 'r') as f:
        for line in f:
            feature = _filter_gff.parse_feature(line)

            if all_filters:
                all_true = _filter_gff.apply_filters(feature,
                                                     all_filters,
                                                     'ALL')
            else:
                all_true = True

            if any_filters:
                any_true = _filter_gff.apply_filters(feature,
                                                     any_filters,
                                                     'ANY')
            else:
                any_true = True

            if all_true and any_true:
                print(line.strip())


if __name__ == '__main__':
    main()
